export const NitroModules = {
  createHybridObject: jest.fn(() => ({
    ping: jest.fn(() => 'pong'),
    getVersion: jest.fn(() => '1.0.0-test'),
    startCamera: jest.fn(),
    stopCamera: jest.fn(),
    capturePhoto: jest.fn(),
    setFlash: jest.fn(),
    setZoom: jest.fn(),
    detectDocument: jest.fn(),
    cropAndCorrect: jest.fn(),
    scanDocument: jest.fn(),
    setOnDocumentDetected: jest.fn(),
    scanBarcodes: jest.fn(),
    startContinuousScan: jest.fn(),
    stopContinuousScan: jest.fn(),
    recognizeText: jest.fn(),
    recognizeDocument: jest.fn(),
    setOnTextRecognized: jest.fn(),
    configure: jest.fn(),
    extractDocument: jest.fn(),
    isLocalLlmModelReady: jest.fn(() => false),
    downloadLocalLlmModel: jest.fn(),
    unloadLocalLlmModel: jest.fn(),
  })),
};
